- Reports error in FormatTranslators.py when running `python test2.py`:
    File "FormatTranslators.py", line 734, in ReadNetFile
    self.insts[inst_name].AddInputPin(MacroPin(pin_name, inst_name, offset[0], offset[1]), "MACRO")
    TypeError: __init__() missing 1 required positional argument: 'macro_type'

- Fix: Adds Marco type parameter when calling MacroPin function.

- The bug is similar to issue #39.

Signed-off-by: mumu <zhuls97@163.com>